# Generated by Django 6.0 on 2025-12-07 09:33

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visualization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='自动生成的名称', max_length=200)),
                ('input_data', models.TextField(help_text='用户输入的原始序列化字符串')),
                ('processed_data', models.TextField(blank=True, help_text='提取最外层花括号后的数据')),
                ('dot_source', models.TextField(blank=True, help_text='Graphviz DOT源码')),
                ('graph_image', models.ImageField(blank=True, null=True, upload_to='visualizations/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '可视化记录',
                'verbose_name_plural': '可视化记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
