# Generated by Django 6.0 on 2025-12-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='session_key',
            field=models.CharField(blank=True, help_text='用户会话ID，用于隔离数据', max_length=100),
        ),
        migrations.AddIndex(
            model_name='visualization',
            index=models.Index(fields=['session_key'], name='visualizer__session_4ecd3f_idx'),
        ),
        migrations.AddIndex(
            model_name='visualization',
            index=models.Index(fields=['created_at'], name='visualizer__created_b36b37_idx'),
        ),
    ]
